services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:alpine-7.0-latest
    container_name: zabbix-proxy
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - ./zbx_proxy_data:/var/lib/zabbix/db_data_sqlite:rw
      - ../zbx_scripts:/usr/lib/zabbix/alertscripts:ro
      - ../zbx_mibs:/var/lib/zabbix/mibs:ro
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    environment:
      - ZBX_PROXYNAME=Zabbix-Proxy-01
      - ZBX_SERVER_HOST=zabbix-server  # Assumindo que o server está em outra rede; ajuste se necessário
      - ZBX_SERVER_PORT=10051
      - ZBX_HOSTNAME=Zabbix-Proxy-01
      - ZBX_CONFIGFREQUENCY=300
      - ZBX_DATABASETYPE=sqlite3
      - ZBX_DB_NAME=zabbix_proxy.db
    networks:
      - zabbix-proxy-net

networks:
  zabbix-proxy-net:
    driver: bridge
